apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: kind
registry: ctlptl-registry
kindV1Alpha4Cluster:
  name: tilt
  nodes:
    - role: control-plane
    - role: worker
    - role: worker
    - role: worker