---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: gitea
  name: gitea
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-config
  namespace: gitea
data:
  app.ini: |
    APP_NAME = Gitea: Git with a cup of tea
    RUN_MODE = prod
    RUN_USER = git

    [repository]
    ROOT = /data/git/repositories

    [repository.local]
    LOCAL_COPY_PATH = /data/gitea/tmp/local-repo

    [repository.upload]
    TEMP_PATH = /data/gitea/uploads

    [server]
    APP_DATA_PATH    = /data/gitea
    DOMAIN           = localhost
    SSH_DOMAIN       = localhost
    HTTP_PORT        = 3000
    ROOT_URL         = http://localhost:3000/
    DISABLE_SSH      = false
    SSH_PORT         = 22
    SSH_LISTEN_PORT  = 22
    LFS_START_SERVER = true
    LFS_CONTENT_PATH = /data/git/lfs
    LFS_JWT_SECRET   = hlqu-okkmi8Wcvtq9BTpmIF3HTe-x2NO6u-3kMnMJ8o
    OFFLINE_MODE     = false

    [database]
    PATH     = /data/gitea/gitea.db
    DB_TYPE  = sqlite3
    HOST     = localhost:3306
    NAME     = gitea
    USER     = root
    PASSWD   = 
    LOG_SQL  = false
    SCHEMA   = 
    SSL_MODE = disable
    CHARSET  = utf8

    [indexer]
    ISSUE_INDEXER_PATH = /data/gitea/indexers/issues.bleve

    [session]
    PROVIDER_CONFIG = /data/gitea/sessions
    PROVIDER        = file

    [picture]
    AVATAR_UPLOAD_PATH            = /data/gitea/avatars
    REPOSITORY_AVATAR_UPLOAD_PATH = /data/gitea/repo-avatars
    DISABLE_GRAVATAR              = false
    ENABLE_FEDERATED_AVATAR       = true

    [attachment]
    PATH = /data/gitea/attachments

    [log]
    MODE      = console
    LEVEL     = info
    ROUTER    = console
    ROOT_PATH = /data/gitea/log

    [security]
    INSTALL_LOCK                  = true
    SECRET_KEY                    = 
    REVERSE_PROXY_LIMIT           = 1
    REVERSE_PROXY_TRUSTED_PROXIES = *
    INTERNAL_TOKEN                = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE2NjAxNTA0MDl9.xNMRYs5EeNcDVr39BghVcoa_4PZT8-5y-zAJP9eP6C8
    PASSWORD_HASH_ALGO            = pbkdf2

    [webhook]
    ALLOWED_HOST_LIST              = webhook-eventsource-svc.workflows.svc.cluster.local

    [service]
    DISABLE_REGISTRATION              = false
    REQUIRE_SIGNIN_VIEW               = false
    REGISTER_EMAIL_CONFIRM            = false
    ENABLE_NOTIFY_MAIL                = false
    ALLOW_ONLY_EXTERNAL_REGISTRATION  = false
    ENABLE_CAPTCHA                    = false
    DEFAULT_KEEP_EMAIL_PRIVATE        = false
    DEFAULT_ALLOW_CREATE_ORGANIZATION = true
    DEFAULT_ENABLE_TIMETRACKING       = true
    NO_REPLY_ADDRESS                  = noreply.localhost

    [mailer]
    ENABLED = false

    [openid]
    ENABLE_OPENID_SIGNIN = true
    ENABLE_OPENID_SIGNUP = true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gitea
  name: gitea
  labels:
    app: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - name: gitea
          image: gitea/gitea:1.16.9
          volumeMounts:
            - mountPath: /data/gitea/conf/
              name: config
          env:
            - name: USER_UID
              value: "1000"
            - name: USER_GID
              value: "1000"
          ports:
            - containerPort: 3000
              name: http
            - containerPort: 22
              name: ssh
      volumes:
        - name: config
          configMap:
            name: gitea-config
            items:
              - key: app.ini
                path: app.ini
---
apiVersion: v1
kind: Service
metadata:
  namespace: gitea
  name: gitea
spec:
  selector:
    app: gitea
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http
    - protocol: TCP
      port: 22
      targetPort: 22
      name: ssh
