---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/example/

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: example-deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
