---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: go-build
  namespace: workflows
spec:
  serviceAccountName: argo-workflow
  entrypoint: go-build
  volumes:
    - name: dagger-conn
      hostPath:
        path: /var/run/dagger
  templates:
    - name: go-build
      inputs:
        parameters:
          - name: message
      container:
        image: go-build
        command: ["ci-helper"]
        env:
          - name: "_EXPERIMENTAL_DAGGER_RUNNER_HOST"
            value: "unix:///var/run/dagger/buildkitd.sock"
        volumeMounts:
          - name: dagger-conn
            mountPath: /var/run/dagger